# Generated by Django 3.1.1 on 2020-09-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ELE', 'Electric'), ('PLU', 'Plumbing'), ('LIG', 'Light fixtures')], max_length=3)),
                ('priority', models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH')], max_length=1)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('unit_id', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'New Ticket'), ('PEN', 'Pending'), ('COM', 'Completed')], max_length=3)),
                ('date_created', models.TimeField()),
                ('completion_date', models.TimeField()),
            ],
        ),
    ]
