# Generated by Django 3.1.1 on 2020-09-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200921_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Ticket'), ('PEN', 'Pending'), ('COM', 'Completed')], default='NEW', max_length=3),
        ),
    ]
