# Generated by Django 3.1.1 on 2020-09-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('ELE', 'Electric'), ('PLU', 'Plumbing'), ('LIG', 'Light fixtures'), ('HAC', 'Heating - AC'), ('ELV', 'Elevators'), ('DOR', 'Doors & Locks'), ('WIN', 'Windows'), ('FLR', 'Floors'), ('EXT', 'Exterminator'), ('OTR', 'Other')], max_length=3),
        ),
    ]
